# Generated by Django 4.2.17 on 2026-04-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=64, unique=True)),
                ('bot_or_human', models.CharField(max_length=20)),
                ('skill_level', models.CharField(max_length=20)),
                ('behavior_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttackLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=50)),
                ('intent_summary', models.TextField(blank=True)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=64)),
                ('user_agent', models.TextField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('request_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PromptAttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=64)),
                ('prompt_text', models.TextField()),
                ('detected_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('query_string', models.TextField(blank=True)),
                ('headers_text', models.TextField(blank=True)),
                ('payload_text', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('status_code', models.IntegerField(null=True)),
                ('duration_ms', models.IntegerField(null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HoneypotApp.attacksession')),
            ],
        ),
        migrations.AddIndex(
            model_name='attacksession',
            index=models.Index(fields=['ip_address', 'user_agent', 'last_seen'], name='HoneypotApp_ip_addr_0e693c_idx'),
        ),
        migrations.AddField(
            model_name='attacklabel',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HoneypotApp.requestevent'),
        ),
        migrations.AddIndex(
            model_name='requestevent',
            index=models.Index(fields=['session'], name='HoneypotApp_session_2bdc8c_idx'),
        ),
        migrations.AddIndex(
            model_name='requestevent',
            index=models.Index(fields=['ip_address', 'created_at'], name='HoneypotApp_ip_addr_5d840f_idx'),
        ),
    ]
